### ISSUE TITLE
Add upper bound to `errors` dependency

### ISSUE THREAD

**Issue by Gabriella439** [bennofs/themplate#1]
`errors-2.0` will switch to use `ExceptT` instead of `EitherT`.  If that will break your package then add an upper bound of `errors < 2.0` to your dependencies.

**Comment by bennofs** [comment]
Thanks for the notice. I will verify this later.

**Comment by bennofs** [comment]
Ok, added an upper bound. Thanks again.

**Comment by Gabriella439** [comment]
You're welcome!
